CREATE DATABASE IF NOT EXISTS motorlab CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE usuario (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  nome VARCHAR(70) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  cargo ENUM('ATENDENTE', 'MECANICO', 'GERENTE') NOT NULL,
) ENGINE=InnoDB;

CREATE TABLE cliente (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  nome VARCHAR(70) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  email VARCHAR(60) NOT NULL,
  endereco TEXT NOT NULL,
) ENGINE=InnoDB;

CREATE TABLE veiculo (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cliente_id INT NOT NULL,
  placa VARCHAR(07) NOT NULL,
  chassi VARCHAR(17) NOT NULL,
  marca VARCHAR(30) NOT NULL,
  modelo VARCHAR(70) NOT NULL,
  ano INT NOT NULL,
  quilometragem INT NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE peca (
  id INT PRIMARY KEY AUTO_INCREMENT,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nome VARCHAR(30) NOT NULL, 
  descricao VARCHAR(70) NULL,
  preco_venda DECIMAL(10,2) NOT NULL,
  estoque INT NOT NULL,
  estoque_minimo INT NOT NULL,
  localizacao VARCHAR(20)
) ENGINE=InnoDB;